config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'card/new'
    get 'card/show'
  end
	root 'users/users#home'

	devise_for :admins
  devise_for :on_store_users, controllers: {
    sessions:      'on_store_users/sessions',
    #passwords:     'users/passwords',
    #registrations: 'users/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    #passwords:     'users/passwords',
    #registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :users do
    devise_scope :user do
      get '/logout', to: 'sessions#destroy', as: 'logout'
    end
  end

  namespace :users do
  	get '/about' => 'users#about', as: 'about'
  	get '/shops' => 'on_store_users#index', as: 'on_store_users_index'
  	get '/shops/:id'    => 'on_store_users#show', as: 'on_store_users_show'
    get '/shops/search' => 'on_store_users#search', as: 'search'
    resources :users ,only:[:show, :edit, :update, :destroy] do
      get '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      get '/shops/:shop_id/inquiry/new' => 'inquiries#new', as: 'inquiry_new'
      post '/shops/:shop_id/inquiry' => 'inquiries#create', as: 'inquiry_create'
      get '/shops/:shop_id/inquiries' => 'inquiries#inquiry', as: 'inquiries_key'
  		resources :inquiries, only:[:index, :show] do
  			resources :replies, only:[:new, :create]
  		end
  		resources :orders, except:[:destroy] do
  			resources :reviews, except:[:index]
		 		resources :inquiries, only:[] do
  				resources :replies, only:[:new, :create, :show]
  			end
		  end
      resources :card, only: [:new, :show] do
        collection do
          post 'show', to: 'card#show'
          post 'pay', to: 'card#pay'
          post 'delete', to: 'card#delete'
        end
      end
  	end
  end

  namespace :on_store_users do
  	get '/form' => 'on_store_users#form', as: 'form'
    post '/form/ok' => 'on_store_users#form', as: 'form_ok'
    resources :on_store_users ,only:[:show, :edit, :update, :destroy] do
    	# get '/sales' => 'on_store_users#sales', as: 'sales'
      get '/home' => 'on_store_users#home', as: 'home'
      get '/withdrawal' => 'on_store_users#withdrawal', as: 'withdrawal'
      resources :on_store_user_images ,only:[:edit, :destroy]
    	resources :reviews, only:[:index, :destroy]
    	resources :inquiries, only:[:index, :show] do
  			resources :replies, only:[:new, :create]
  		end
  		resources :orders, except:[:create] do
        resources :order_images, only:[:destroy]
		 		resources :inquiries, except:[:destroy, :edit, :update] do
  				resources :replies, only:[:new, :create, :show]
  			end
		  end
  	end
  end

  namespace :on_store_users do
    devise_scope :on_store_user do
      get '/logout', to: 'sessions#destroy', as: 'logout'
    end
  end

  namespace :admins do
    get '', to:'admins#home'
    resources :orders, only:[:index, :show]
    resources :users, except:[:edit]
    resources :on_store_users, except:[:edit]
    resources :inquiries, only:[:index, :show]
    resources :reviews, only:[:index, :show, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/admins/reviews_controller.rb
class Admins::ReviewsController < ApplicationController
	before_action :authenticate_admin!

	def index
		if params[:search].present?
			@q = Review.ransack(search_params)
			@reviews = @q.result(distinct: true).page(params[:page]).reverse_order
		else
			@q = Review.ransack(params[:q])
			@reviews = @q.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def destroy
		@q = Review.ransack(params[:q])
		@reviews = @q.result(distinct: true).page(params[:page]).reverse_order
		review = Review.find(params[:id])
		review.destroy
		redirect_to admins_reviews_path
	end

	def search_params
    params.require(:q).permit(:s,
    													:user_name_cont,
    													:on_store_user_shop_name_cont)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!

	def index
		if params[:search].present?
			@q = User.ransack(search_params)
			@users = @q.result(distinct: true).page(params[:page]).reverse_order
		else
			@q = User.ransack(params[:q])
			@users = @q.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		user.is_quit = "利用中"
		user.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		user = User.find(params[:id])
		user.is_quit = "退会済み"
		user.save
		redirect_back(fallback_location: root_path)
	end

	private
	def search_params
    params.require(:q).permit(:s,
    													:name_cont,
    													:telephone_number_cont,
    													:email_cont)
  end

end

app/controllers/on_store_users/reviews_controller.rb
class OnStoreUsers::ReviewsController < ApplicationController
	before_action :authenticate_on_store_user!
	# URLの直接入力を弾く
	before_action :ensure_correct_on_store_user
  def ensure_correct_on_store_user
    if current_on_store_user.id != params[:on_store_user_id].to_i
      redirect_to on_store_users_on_store_user_home_path(current_on_store_user)
    end
  end

	def index
		@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)
		if params[:search].present?
			@q = current_on_store_user.reviews.ransack(search_params)
			@reviews = @q.result(distinct: true).page(params[:page]).reverse_order
		else
			@q = current_on_store_user.reviews.ransack(params[:q])
			@reviews = @q.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def destroy
		@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)
		@q = current_on_store_user.reviews.ransack(params[:q])
		@reviews = @q.result(distinct: true).page(params[:page]).reverse_order
		review = Review.find(params[:id])
		review.destroy
		redirect_to on_store_users_on_store_user_reviews_path(current_on_store_user)
	end

	def search_params
    params.require(:q).permit(:s, :user_name_cont)
  end
end

app/controllers/users/card_controller.rb
class Users::CardController < ApplicationController
  require "payjp"

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to edit_users_user_path(current_user)
    else
      customer = Payjp::Customer.create(
      email: current_user.email,
      card: params['payjp-token']
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to users_user_path(current_user)
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to users_user_path(current_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/inquiries_controller.rb
class Users::InquiriesController < ApplicationController
	before_action :authenticate_user!
	# URL直入力弾く
	before_action :ensure_correct_user
	def ensure_correct_user
		if current_user.id != params[:user_id].to_i
			redirect_to root_path
		end
	end

	def new
		@inquiry = Inquiry.new
		@user = current_user
		@shop = OnStoreUser.find(params[:shop_id])
		@inquiry_creat_url = "/users/users/#{@user.id}/shops/#{@shop.id}/inquiry"
		if params[:order_id]
			@order = Order.find(params[:order_id])
		end

		respond_to do |format|
	    format.html
	    format.js {render '/shared/inquiries/new.js.erb'}
	   end
	end

	def create
		inquiry = current_user.inquiries.new(inquiry_params)
		@shop = OnStoreUser.find(params[:shop_id])
		inquiry.on_store_user_id = @shop.id
		inquiry.user_read = true
		# 注文前の問合せか後か
		if params[:inquiry][:order_id].present?
			@order = Order.find(params[:inquiry][:order_id])
			inquiry.order_id = @order.id
		end
		inquiry.save
		if params[:inquiry][:order_id].present?
			# partial表示のためのインスタンス変数（注文に対する）
			@inquiries = @order.inquiries
		else
			# partial表示のためのインスタンス変数（注文前）
			@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
		end
		# 出店者へ通知
		OnStoreUserMailer.with(on_store_user: @shop, inquiry: inquiry).new_inquiry.deliver_later

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		end
	end

	def index
		@user = current_user
		@q = @user.inquiries.ransack(params[:q])
		@inquiries = @q.result(distinct: true).page(params[:page]).reverse_order

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/index.js.erb'}
		end
	end

	def inquiry
		@shop = OnStoreUser.find(params[:shop_id])
		if params[:order_id] != nil
			@order = Order.find(params[:order_id])
			@inquiries = @order.inquiries
		else
			@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
		end

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		 end
	end

	def show
		@user = current_user
		@shop = OnStoreUser.find(params[:shop_id])
		@inquiry = Inquiry.find(params[:id])
		@reply_new_url = "/users/users/#{@user.id}/inquiries/#{@inquiry.id}/replies/new"
		if params[:partial_key].present?
			@partial_key = params[:partial_key]
		end
		if params[:order_id].present?
			@order = Order.find(params[:order_id])
			@reply_new_url = "/users/users/#{@user.id}/orders/#{@order.id}/inquiries/#{@inquiry.id}/replies/new"
		end
		# 既読処理
		@inquiry.user_read = true
		@inquiry.save

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/show.js.erb'}
		 end
	end

	private
	def inquiry_params
		params.require(:inquiry).permit(:on_store_user_id,
																		:order_id,
																		:user_id,
																		:title,
																		:body,
																		:is_read)
	end

	def search_params
    params.require(:q).permit(:s)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/on_store_users_controller.rb
class Users::OnStoreUsersController < ApplicationController

	def index
  	if params[:q].present?
  		@q = OnStoreUser.includes(major_categories: {middle_categories: :minor_categories}).ransack(search_params)
  		@shops = @q.result(distinct: true).public_and_is_quit?.page(params[:page]).reverse_order
      @search_by = []
      @search_by = @search_by + [params[:q][:address_cont]]
      @search_by = @search_by + [params[:q][:major_categories_name_or_major_categories_middle_categories_name_or_major_categories_middle_categories_minor_categories_name_cont]]
    else
      @q = OnStoreUser.includes(major_categories: {middle_categories: :minor_categories}).ransack(params[:q])
      @shops = @q.result(distinct: true).public_and_is_quit?.page(params[:page]).reverse_order
    end
	end

	def show
		@shop = OnStoreUser.find(params[:id])
		@reviews = @shop.reviews.page(params[:page]).reverse_order
		@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
	end

	private
	def search_params
    params.require(:q).permit(:address_cont,
                              :major_categories_name_or_major_categories_middle_categories_name_or_major_categories_middle_categories_minor_categories_name_cont)
  end

end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
	before_action :authenticate_user!
	# URL直入力弾く
	before_action :ensure_correct_user
	def ensure_correct_user
		if current_user.id != params[:user_id].to_i
			redirect_to root_path
		end
	end

	def new
		@user = current_user
		@shop = OnStoreUser.find(params[:on_store_user_id])
		@order = Order.new
	end

	def create
		@user = current_user
		@order = @user.orders.new(order_params)
		@order.serial_number = @order.on_store_user.orders.count + 1
		if @order.save
			# 出店者へ通知
			OnStoreUserMailer.with(order: @order).new_order.deliver_later
			redirect_to users_user_order_path(@user, @order)
		else
			@shop = @order.on_store_user
			render :new
		end
	end

	def show
		@user = current_user
		@order = Order.find(params[:id])
		@inquiries = @order.inquiries
	end

	def edit
		@user =current_user
		@order = Order.find(params[:id])

		respond_to do |format|
	  	format.html
	  	format.js
	  end
	end

	def update
		@user = current_user
		@order = Order.find(params[:id])
		@order.update(order_params)
		if @order.repair_status == "修理完了"
			@order.repair_status = "支払済み"
		else
			@order.repair_status = "取引完了"
		end
		@order.save
		# 出店者へ通知
		OnStoreUserMailer.with(order: @order).update_order.deliver_later
		if params[:commit] == "後でする"
			redirect_to users_user_order_path(@user, @order)
		else
			@review_create_key = true
			respond_to do |format|
		  	format.html
		  	format.js {render '/users/reviews/new.js.erb', order: @order, user: @user, review_create_key: @review_create_key}
		  end
		end
	end

	private
	def order_params
		params.require(:order).permit(:user_id,
																	:on_store_user_id,
																	:variety,
																	:pickup,
																	:maker,
																	:model,
																	:symptom,
																	:repair_status,
																	:repair_detail,
																	:payment,
																	:charge,
																	:delivery,
																	:delivery_day,
																	order_images_images: [])
	end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/reviews_helper.rb
module Admins::ReviewsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/on_store_users/reviews_helper.rb
module OnStoreUsers::ReviewsHelper
end

app/views/users/reviews/_edit.html.erb
	<h2 class="font-size4" style="margin-bottom: 20px;"><strong>レビュー編集中</strong></h4>
	<%= form_with model: @review, url: users_user_order_review_path(@user, @order, @review) do |f| %>
		<div class="row">
			<div class="field font-size3 col-sm-8 col-xs-8" style="margin-bottom: 30px">
			  <%= f.label :title, "レビュータイトル" %><br/>
			  <%= f.text_field :title, placeholder: 'タイトル(50文字以内):', class: "col-sm-8 col-xs-8" %>
			</div>
	 </div>
		<div class="row">
			<div class="field font-size3 col-sm-12 col-xs-12" style="margin-bottom: 30px">
			  <%= f.label :body, "本文" %><br/>
			  <%= f.text_area :body, placeholder: '本文(1000文字以内):', rows:10, style: "resize: none;", class: "col-sm-12 col-xs-12" %>
	 		</div>
		</div>
		<div class="actions col-sm-4 col-xs-4" style="margin-bottom: 20px">
			<%= f.submit "確定", name: "edit_review", class: "btn btn-info font-size3" %>
		</div>
		<div class="actions col-sm-4 col-xs-4" style="margin-bottom: 20px">
			<%= link_to "キャンセル", users_user_order_path(@user, @order), class: "btn btn-default font-size3" %>
		</div>
	<% end %>

app/views/users/reviews/_new.html.erb
<div class="col-md-10 col-xs-12 col-md-offset-1">
	<h2 class="font-size4" style="margin-bottom: 20px;"><strong>修理店を評価する</strong></h4>

	<%= form_with model: Review.new, url: users_user_order_reviews_path(@user, @order) do |f| %>

		<div class="row">
			<div class="form-group font-size3 col-sm-8 col-xs-8" style="margin-bottom: 30px">
			  <%= f.label :title, "レビュータイトル" %><br/>
			  <%= f.text_field :title, placeholder: 'タイトル(50文字以内):', class: "form-control form-height font-size3" %>
			</div>
	 </div>
		<div class="row">
			<div class="form-group font-size3 col-sm-12 col-xs-12" style="margin-bottom: 30px">
			  <%= f.label :body, "本文" %><br/>
			  <%= f.text_area :body, rows:10, placeholder: '本文(1000文字以内):', style: "resize: none;", class: "form-control font-size3" %>
	 		</div>
		</div>

		<% if defined? @review_create_key %>
			<%= f.hidden_field :review_create_key, :value => @review_create_key %>
		<% end %>

		<div class="actions col-sm-4 col-xs-4" style="margin-bottom: 50px">
			<%= f.submit "投稿する", name: "new_review", class: "btn btn-info font-size3" %>
		</div>
		<div class="col-sm-4 col-xs-4" style="margin-bottom: 50px">
			<%= link_to "後でする", users_user_order_path(@user, @order), class: "btn btn-default font-size3" %>
		</div>
	<% end %>
</div>

app/views/users/reviews/_show.html.erb
<table class="table font-size3">
	<tbody>
		<tr>
			<td class="cell-title" style="border-top: none;">タイトル：</td>
			<td class="cell-body" style="border-top: none;"><%= @order.reviews.first.title %></td>
		</tr>
		<tr>
			<% if @order.reviews.first.created_at == @order.reviews.first.updated_at %>
				<td class="cell-title">投稿日</td>
				<td class="cell-body">
					<%= @order.reviews.first.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@order.created_at.wday]}) %H:%M") %>
				</td>
			<% else %>
				<td class="cell-title">更新日</td>
				<td class="cell-body">
					<%= @order.reviews.first.updated_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@order.created_at.wday]}) %H:%M") %>
				</td>
			<% end %>
		</tr>
		<tr>
			<td class="cell-title">本文：</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="2" style="border-top: none;"><%= text_br(@order.reviews.first.body) %></td>
		</tr>
	</tbody>
</table>

<% if defined? @user %>
	<div class="row">
		<div class="actions col-sm-4 col-xs-4" style="margin-bottom: 20px">
			<%= link_to "編集する", edit_users_user_order_review_path(@user, @order, @order.reviews.first), remote: true, class: "btn btn-info font-size3" %>
		</div>
		<div class="actions col-sm-4 col-xs-4" style="margin-bottom: 20px">
			<%= link_to "削除する", users_user_order_review_path(@user, @order, @order.reviews.first), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger font-size3" %>
		</div>
	</div>
<% end %>

app/views/users/reviews/edit.js.erb
$(".review_section").html("<%= escape_javascript(render partial:'/users/reviews/edit') %>");

app/views/users/reviews/new.js.erb
$(".review_section").html("<%= escape_javascript(render partial:'/users/reviews/new') %>");

app/views/users/reviews/show.js.erb
$(".review_section").html("<%= escape_javascript(render partial:'/users/reviews/show') %>");