config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'card/new'
    get 'card/show'
  end
	root 'users/users#home'

	devise_for :admins
  devise_for :on_store_users, controllers: {
    sessions:      'on_store_users/sessions',
    #passwords:     'users/passwords',
    #registrations: 'users/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    #passwords:     'users/passwords',
    #registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :users do
    devise_scope :user do
      get '/logout', to: 'sessions#destroy', as: 'logout'
    end
  end

  namespace :users do
  	get '/about' => 'users#about', as: 'about'
  	get '/shops' => 'on_store_users#index', as: 'on_store_users_index'
  	get '/shops/:id'    => 'on_store_users#show', as: 'on_store_users_show'
    get '/shops/search' => 'on_store_users#search', as: 'search'
    resources :users ,only:[:show, :edit, :update, :destroy] do
      get '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      get '/shops/:shop_id/inquiry/new' => 'inquiries#new', as: 'inquiry_new'
      post '/shops/:shop_id/inquiry' => 'inquiries#create', as: 'inquiry_create'
      get '/shops/:shop_id/inquiries' => 'inquiries#inquiry', as: 'inquiries_key'
  		resources :inquiries, only:[:index, :show] do
  			resources :replies, only:[:new, :create]
  		end
  		resources :orders, except:[:destroy] do
  			resources :reviews, except:[:index]
		 		resources :inquiries, only:[] do
  				resources :replies, only:[:new, :create, :show]
  			end
		  end
      resources :card, only: [:new, :show] do
        collection do
          post 'show', to: 'card#show'
          post 'pay', to: 'card#pay'
          post 'delete', to: 'card#delete'
        end
      end
  	end
  end

  namespace :on_store_users do
  	get '/form' => 'on_store_users#form', as: 'form'
    post '/form/ok' => 'on_store_users#form', as: 'form_ok'
    resources :on_store_users ,only:[:show, :edit, :update, :destroy] do
    	# get '/sales' => 'on_store_users#sales', as: 'sales'
      get '/home' => 'on_store_users#home', as: 'home'
      get '/withdrawal' => 'on_store_users#withdrawal', as: 'withdrawal'
      resources :on_store_user_images ,only:[:edit, :destroy]
    	resources :reviews, only:[:index, :destroy]
    	resources :inquiries, only:[:index, :show] do
  			resources :replies, only:[:new, :create]
  		end
  		resources :orders, except:[:create] do
        resources :order_images, only:[:destroy]
		 		resources :inquiries, except:[:destroy, :edit, :update] do
  				resources :replies, only:[:new, :create, :show]
  			end
		  end
  	end
  end

  namespace :on_store_users do
    devise_scope :on_store_user do
      get '/logout', to: 'sessions#destroy', as: 'logout'
    end
  end

  namespace :admins do
    get '', to:'admins#home'
    resources :orders, only:[:index, :show]
    resources :users, except:[:edit]
    resources :on_store_users, except:[:edit]
    resources :inquiries, only:[:index, :show]
    resources :reviews, only:[:index, :show, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
	before_action :authenticate_admin!

	def index
		if params[:search].present?
			@q = Order.ransack(search_params)
			@orders = @q.result(distinct: true).page(params[:page]).reverse_order
		else
			@q = Order.ransack(params[:q])
			@orders = @q.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def show
		@order = Order.find(params[:id])
	end

	def search_params
    params.require(:q).permit(:s,
    													:shop_name_cont,
    													:owner_name_cont,
    													:telephone_number_cont,
    													:email_cont)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!

	def index
		if params[:search].present?
			@q = User.ransack(search_params)
			@users = @q.result(distinct: true).page(params[:page]).reverse_order
		else
			@q = User.ransack(params[:q])
			@users = @q.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		user.is_quit = "利用中"
		user.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		user = User.find(params[:id])
		user.is_quit = "退会済み"
		user.save
		redirect_back(fallback_location: root_path)
	end

	private
	def search_params
    params.require(:q).permit(:s,
    													:name_cont,
    													:telephone_number_cont,
    													:email_cont)
  end

end

app/controllers/on_store_users/orders_controller.rb
class OnStoreUsers::OrdersController < ApplicationController
	before_action :authenticate_on_store_user!
	# URLの直接入力を弾く
	before_action :ensure_correct_on_store_user
  def ensure_correct_on_store_user
    if current_on_store_user.id != params[:on_store_user_id].to_i
      redirect_to on_store_users_on_store_user_home_path(current_on_store_user)
    end
  end

	def index
		if params[:search].present? || params[:q].present?
			if params[:q].present?
				@q = current_on_store_user.orders.ransack(search_params)
				@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)
				@orders = @q.result(distinct: true).page(params[:page]).reverse_order
			else
				@q = current_on_store_user.orders.ransack(params[:q])
				@search = current_on_store_user.orders.ransack(telephone_number_search_params)
				@orders = @search.result(distinct: true).page(params[:page]).reverse_order
			end
		else
			@q = current_on_store_user.orders.ransack(params[:q])
			@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)
			@orders = @search.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def show
		@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)
		@order = Order.find(params[:id])

		if params[:key] == "repair"
			respond_to do |format|
		  	format.html
		  	format.js {render '/on_store_users/orders/repair_detail.js.erb'}
		  end
		end

		respond_to do |format|
	  	format.html
	  	format.js
	  end
	end

	def edit
		@order = Order.find(params[:id])
		if params[:key] == "charge"

			respond_to do |format|
		  	format.html
		  	format.js {render '/on_store_users/orders/charge.js.erb'}
		  end
		elsif params[:key] == "repair"

			respond_to do |format|
		  	format.html
		  	format.js {render '/on_store_users/orders/repair_edit.js.erb'}
		  end
		end

		respond_to do |format|
	  	format.html
	  	format.js
	  end
	end

	def update
		@order = Order.find(params[:id])
		@order.update(order_params)
		# エンドユーザへ通知
		UserMailer.with(order: @order).update_order.deliver_later

		if params[:order][:repair_key].present?
			if @order.repair_status == "取引完了"
				redirect_to on_store_users_on_store_user_order_path(current_on_store_user, @order)
			else
				respond_to do |format|
			  	format.html
			  	format.js {render '/on_store_users/orders/repair_detail.js.erb'}
			  end
			end
		else
			respond_to do |format|
		  	format.html {redirect_to on_store_users_on_store_user_order_path(current_on_store_user, @order)}
		  	format.js {render '/on_store_users/orders/show.js.erb'}
		  end
		end
	end

	private
	def order_params
		params.require(:order).permit(:user_id,
																	:on_store_user_id,
																	:variety,
																	:pickup,
																	:maker,
																	:model,
																	:symptom,
																	:repair_status,
																	:repair_detail,
																	:payment,
																	:charge,
																	:delivery,
																	:delivery_day,
																	order_images_images: [])
	end

	def telephone_number_search_params
		params.require(:search).permit(:user_telephone_number_cont)
  end
  def search_params
		params.require(:q).permit(:s,
    															:user_name_cont,
			   													:repair_status_eq,
			   													:variety_eq)
  end
end

app/controllers/users/card_controller.rb
class Users::CardController < ApplicationController
  require "payjp"

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to edit_users_user_path(current_user)
    else
      customer = Payjp::Customer.create(
      email: current_user.email,
      card: params['payjp-token']
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to users_user_path(current_user)
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to users_user_path(current_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/inquiries_controller.rb
class Users::InquiriesController < ApplicationController
	before_action :authenticate_user!
	# URL直入力弾く
	before_action :ensure_correct_user
	def ensure_correct_user
		if current_user.id != params[:user_id].to_i
			redirect_to root_path
		end
	end

	def new
		@inquiry = Inquiry.new
		@user = current_user
		@shop = OnStoreUser.find(params[:shop_id])
		@inquiry_creat_url = "/users/users/#{@user.id}/shops/#{@shop.id}/inquiry"
		if params[:order_id]
			@order = Order.find(params[:order_id])
		end

		respond_to do |format|
	    format.html
	    format.js {render '/shared/inquiries/new.js.erb'}
	   end
	end

	def create
		inquiry = current_user.inquiries.new(inquiry_params)
		@shop = OnStoreUser.find(params[:shop_id])
		inquiry.on_store_user_id = @shop.id
		inquiry.user_read = true
		# 注文前の問合せか後か
		if params[:inquiry][:order_id].present?
			@order = Order.find(params[:inquiry][:order_id])
			inquiry.order_id = @order.id
		end
		inquiry.save
		if params[:inquiry][:order_id].present?
			# partial表示のためのインスタンス変数（注文に対する）
			@inquiries = @order.inquiries
		else
			# partial表示のためのインスタンス変数（注文前）
			@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
		end
		# 出店者へ通知
		OnStoreUserMailer.with(on_store_user: @shop, inquiry: inquiry).new_inquiry.deliver_later

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		end
	end

	def index
		@user = current_user
		@q = @user.inquiries.ransack(params[:q])
		@inquiries = @q.result(distinct: true).page(params[:page]).reverse_order

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/index.js.erb'}
		end
	end

	def inquiry
		@shop = OnStoreUser.find(params[:shop_id])
		if params[:order_id] != nil
			@order = Order.find(params[:order_id])
			@inquiries = @order.inquiries
		else
			@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
		end

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		 end
	end

	def show
		@user = current_user
		@shop = OnStoreUser.find(params[:shop_id])
		@inquiry = Inquiry.find(params[:id])
		@reply_new_url = "/users/users/#{@user.id}/inquiries/#{@inquiry.id}/replies/new"
		if params[:partial_key].present?
			@partial_key = params[:partial_key]
		end
		if params[:order_id].present?
			@order = Order.find(params[:order_id])
			@reply_new_url = "/users/users/#{@user.id}/orders/#{@order.id}/inquiries/#{@inquiry.id}/replies/new"
		end
		# 既読処理
		@inquiry.user_read = true
		@inquiry.save

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/show.js.erb'}
		 end
	end

	private
	def inquiry_params
		params.require(:inquiry).permit(:on_store_user_id,
																		:order_id,
																		:user_id,
																		:title,
																		:body,
																		:is_read)
	end

	def search_params
    params.require(:q).permit(:s)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/on_store_users_controller.rb
class Users::OnStoreUsersController < ApplicationController

	def index
  	if params[:q].present?
  		@q = OnStoreUser.includes(major_categories: {middle_categories: :minor_categories}).ransack(search_params)
  		@shops = @q.result(distinct: true).public_and_is_quit?.page(params[:page]).reverse_order
      @search_by = []
      @search_by = @search_by + [params[:q][:address_cont]]
      @search_by = @search_by + [params[:q][:major_categories_name_or_major_categories_middle_categories_name_or_major_categories_middle_categories_minor_categories_name_cont]]
    else
      @q = OnStoreUser.includes(major_categories: {middle_categories: :minor_categories}).ransack(params[:q])
      @shops = @q.result(distinct: true).public_and_is_quit?.page(params[:page]).reverse_order
    end
	end

	def show
		@shop = OnStoreUser.find(params[:id])
		@reviews = @shop.reviews.page(params[:page]).reverse_order
		@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
	end

	private
	def search_params
    params.require(:q).permit(:address_cont,
                              :major_categories_name_or_major_categories_middle_categories_name_or_major_categories_middle_categories_minor_categories_name_cont)
  end

end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
	before_action :authenticate_user!
	# URL直入力弾く
	before_action :ensure_correct_user
	def ensure_correct_user
		if current_user.id != params[:user_id].to_i
			redirect_to root_path
		end
	end

	def new
		@user = current_user
		@shop = OnStoreUser.find(params[:on_store_user_id])
		@order = Order.new
	end

	def create
		@user = current_user
		@order = @user.orders.new(order_params)
		@order.serial_number = @order.on_store_user.orders.count + 1
		if @order.save
			# 出店者へ通知
			OnStoreUserMailer.with(order: @order).new_order.deliver_later
			redirect_to users_user_order_path(@user, @order)
		else
			@shop = @order.on_store_user
			render :new
		end
	end

	def show
		@user = current_user
		@order = Order.find(params[:id])
		@inquiries = @order.inquiries
	end

	def edit
		@user =current_user
		@order = Order.find(params[:id])

		respond_to do |format|
	  	format.html
	  	format.js
	  end
	end

	def update
		@user = current_user
		@order = Order.find(params[:id])
		@order.update(order_params)
		if @order.repair_status == "修理完了"
			@order.repair_status = "支払済み"
		else
			@order.repair_status = "取引完了"
		end
		@order.save
		# 出店者へ通知
		OnStoreUserMailer.with(order: @order).update_order.deliver_later
		if params[:commit] == "後でする"
			redirect_to users_user_order_path(@user, @order)
		else
			@review_create_key = true
			respond_to do |format|
		  	format.html
		  	format.js {render '/users/reviews/new.js.erb', order: @order, user: @user, review_create_key: @review_create_key}
		  end
		end
	end

	private
	def order_params
		params.require(:order).permit(:user_id,
																	:on_store_user_id,
																	:variety,
																	:pickup,
																	:maker,
																	:model,
																	:symptom,
																	:repair_status,
																	:repair_detail,
																	:payment,
																	:charge,
																	:delivery,
																	:delivery_day,
																	order_images_images: [])
	end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/users/orders/edit.html.erb
<div class="container-fluid" style="margin-top: 100px; margin-bottom: 150px; ">
  <div class="body-boder col-md-7 col-xs-11" style="margin-bottom: 50px;">
    <h2 class="font-size5" style="padding-left: 50px;">支払方法の選択</h2>
  </div>
  <div class="col-md-10 margin-left col-xs-12 body-boder" style="margin-bottom: 50px;">
    <div class="col-md-12 col-xs-12 review_section">
      <div class="row" style="padding: 50px 0;">
        <div class="font-size4 col-md-5 col-xs-5">
          <strong>支払料金</strong>
        </div>
        <div class="font-size4 col-md-5 col-xs-5">
          <%= @order.charge.to_s(:delimited) %>円
        </div>
      </div>

      <%= form_with model: @order, url: users_user_order_path(@user, @order) do |f| %>
        <div class="row" style="padding-bottom: 50px;">
          <div class="col-md-9 col-xs-9">
            <h4 class="font-size3" style="margin-bottom: 20px;"><strong>支払方法</strong></h4>
          </div>
          <div class="col-md-7 col-xs-7">
            <ul class="font-size3" style="list-style: none; padding-left: 10px;">
              <li>
                <label><%= f.radio_button :payment, :クレジット支払, checked: true, style: "width: 25px; height: 25px;" %> 現金支払</label>
              </li>
              <li>
                <label><%= f.radio_button :payment, :銀行振込, style: "width: 25px; height: 25px;" %> 銀行振込</label>
              </li>
              <li>
                <label><%= f.radio_button :payment, :クレジット支払, style: "width: 25px; height: 25px;" %> クレジット支払</label>
              </li>
            </ul>
          </div>
        </div>
        <div class="row" style="padding-bottom: 50px;">
          <div class="actions col-md-4 col-xs-4" style="margin-bottom: 20px">
            <%= f.submit "レビューを書く", data: { confirm: "支払方法を確定し、修理店を評価します。" }, class: "btn btn-info font-size3", id: "submit" %>
          </div>
          <div class="actions col-md-4 col-xs-4" style="margin-bottom: 20px">
            <%= f.submit "後でする", data: { confirm: "支払方法を確定します。" }, class: "btn btn-info font-size3" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('#submit').on('click', function() {
    $(".payment").hide();
  });
</script>

app/views/users/orders/show.html.erb
<div class="container-fluid" style="margin-bottom: 150px;">
	<div class="body-boder col-md-7 col-xs-11" style="margin: 50px 0 50px 0;">
		<h2 class="font-size5" style="padding-left: 50px;">注文明細ページ</h2>
	</div>

	<div class="row">
		<div class="col-md-11 margin-left col-xs-12">
			<!-- タブメニュー -->
			<div class="row">
				<div id="tab-menu" class="col-md-10 col-xs-12">
	        <a href="#tab1" class="active col-md-4 col-xs-4 btn btn-default font-size4" style="box-shadow: 10px 10px 10px;">
		      	注文明細
		      </a>
	        <a href="#tab2" class="col-md-4 col-xs-4 btn btn-default font-size4" style="box-shadow: 10px 10px 10px;">
		      	お問合せ
		      </a>
	        <% if @order.payment != nil %>
	        	<a href="#tab3" class="col-md-4 col-xs-4 btn btn-default font-size4" style="box-shadow: 10px 10px 10px;">
		      	レビュー
		      </a>
	        <% end %>
	      </div>
			</div>
			<!-- 注文情報 -->
			<div id="tab1" class="tab body-boder col-md-12 col-xs-12">
				<div class="row">
					<div class="col-md-12" style="padding-top: 20px;">
						<h3 class="font-size4">注文情報</h3>
						<table class="table font-size3">
							<tbody>
								<tr>
									<td class="cell-title">注文ID</td>
									<td class="cell-body"><%= @order.id %></td>
								</tr>
								<tr>
									<td class="cell-title">受付日</td>
									<td class="cell-body"><%= @order.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@order.created_at.wday]}) %H:%M") %></td>
								</tr>
								<tr>
									<td class="cell-title">修理店</td>
									<td class="cell-body"><%= link_to @order.on_store_user.shop_name, users_on_store_users_show_path(@order.on_store_user_id) %></td>
								</tr>
								<tr>
									<td class="cell-title">集荷方法</td>
									<td class="cell-body"><%= @order.pickup %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<div class="row" style="margin-bottom: 50px;">
					<div class="col-md-12">
						<h3 class="font-size4">商品情報</h3>
						<table class="table font-size3">
							<tbody>
								<tr>
									<td class="cell-title">品種</td>
									<td class="cell-body"><%= @order.variety %></td>
								</tr>
								<tr>
									<td class="cell-title">メーカー</td>
									<td class="cell-body"><%= @order.maker %></td>
								</tr>
								<tr>
									<td class="cell-title">型番</td>
									<td class="cell-body"><%= @order.model %></td>
								</tr>
								<tr>
									<td class="cell-title">症状</td>
									<td class="cell-body"><%= text_br(@order.symptom) %></td>
								</tr>
							</tbody>
						</table>
						<% if @order.order_images.count != 0 %>
							<div class="col-md-12 col-xs-12" style="padding-left: 0;">
								<h3 class="font-size4">画像</h3>
								<div style="height: 400px; width: 700px; background-color: gray;">
									<div class="theTarget">
										<% @order.order_images.each do |image| %>
											<div style="padding-left: 40px;"><%= attachment_image_tag image, :image, :fill, 600, 400, format: 'jpeg' %></div>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>

				<div class="row" style="margin-bottom: 50px;">
					<div class="col-md-12">
						<h3 class="font-size4">修理状況</h3>
						<table class="table font-size3">
							<tbody>
								<tr>
									<td class="cell-title">修理状況</td>
									<td class="cell-body"><%= @order.repair_status %></td>
								</tr>
								<tr>
									<td class="cell-title">更新日</td>
									<td class="cell-body"><%= @order.updated_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@order.created_at.wday]}) %H:%M") %></td>
								</tr>
								<tr>
									<td class="cell-title">修理内容</td>
									<td class="cell-body"><%= text_br(@order.repair_detail) %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<div class="row" style="margin-bottom: 20px;">
					<div class="col-md-12">
						<h3 class="font-size4">支払情報</h3>
						<table class="table font-size3">
							<tbody>
								<tr>
									<td class="cell-title">料金</td>
									<td class="cell-body">
										<% if @order.charge == nil %>
											見積前
										<% else %>
											<%= @order.charge.to_s(:delimited) %>円
										<% end %>
									</td>
								</tr>
								<% if @order.repair_status != "集荷前" && @order.repair_status != "見積前" && @order.repair_status != "修理中" && @order.repair_status != "キャンセル" %>
									<tr>
										<% if @order.payment == nil %>
											<td class="cell-title" style="border-top: none;"></td>
											<td class="cell-body" style="border-top: none;"><%= link_to '支払&評価へ進む', edit_users_user_order_path(@user, @order), class: "btn btn-primary font-size3" %></td>
										<% else %>
											<td class="cell-title">支払方法</td>
											<td class="cell-body"><%= @order.payment %></td>
										<% end %>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div>

			<!-- お問合せフォーム -->
			<div id="tab2" class="tab inquiries body-boder col-md-12 col-xs-12" style="min-height: 300px;">
				<%= render '/shared/inquiries/inquiry', inquiries: @order.inquiries, shop: @order.on_store_user,order: @order %>
			</div>

			<!-- レビュー -->
			<% if @order.payment != nil %>
				<div id="tab3" class="tab body-boder col-md-12 col-xs-12" style="min-height: 300px;">
					<% if @user.review_by?(@order) %>
						<div class="col-md-12 col-xs-12 review_section">
							<%= render '/users/reviews/show', order: @order, user: @user %>
						</div>
					<% else %>
						<div class="col-md-12 col-xs-12 review_section" style="margin-top: 30px;">
							<%= link_to "レビューを書く", new_users_user_order_review_path(@user, @order), remote: true, class: "btn btn-primary font-size4", style: "margin: 50px 0 0 25%;" %>
						</div>
					<% end %>
				</div>
			<% end %>

		</div>
	</div>
</div>

<script>
	$('document').on('turbolinks:load', function(){
		$('.theTarget').skippr();
	});

	$('.theTarget').skippr({
		// "fade" or "slide"
		transition: 'slide',
		speed: 500,
		// easingの種類
		easing: 'easeOutQuart',
		// "block" or "bubble"
		navType: 'bubble',
		// "div" or "img"
		childrenElementType: 'div',
		arrows: true,
		// スライドショーの自動再生
		autoPlay: false,
	// キーボードの矢印キーによるスライド送りの設定
		keyboardOnAlways: true,
	// 1枚目のスライド表示時に戻る矢印を表示するか
		hidePrevious: false
	});

	$('.tab[id != "tab1"]').hide();

	$('#tab-menu a').on('click', function() {
  	$(".tab").hide();
  	$("#tab-menu .active").removeClass("active");
  	$(this).addClass("active");
  	$($(this).attr("href")).show();
  	return false;
	});
</script>