config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'card/new'
    get 'card/show'
  end
	root 'users/users#home'

	devise_for :admins
  devise_for :on_store_users, controllers: {
    sessions:      'on_store_users/sessions',
    #passwords:     'users/passwords',
    #registrations: 'users/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    #passwords:     'users/passwords',
    #registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :users do
    devise_scope :user do
      get '/logout', to: 'sessions#destroy', as: 'logout'
    end
  end

  namespace :users do
  	get '/about' => 'users#about', as: 'about'
  	get '/shops' => 'on_store_users#index', as: 'on_store_users_index'
  	get '/shops/:id'    => 'on_store_users#show', as: 'on_store_users_show'
    get '/shops/search' => 'on_store_users#search', as: 'search'
    resources :users ,only:[:show, :edit, :update, :destroy] do
      get '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      get '/shops/:shop_id/inquiry/new' => 'inquiries#new', as: 'inquiry_new'
      post '/shops/:shop_id/inquiry' => 'inquiries#create', as: 'inquiry_create'
      get '/shops/:shop_id/inquiries' => 'inquiries#inquiry', as: 'inquiries_key'
  		resources :inquiries, only:[:index, :show] do
  			resources :replies, only:[:new, :create]
  		end
  		resources :orders, except:[:destroy] do
  			resources :reviews, except:[:index]
		 		resources :inquiries, only:[] do
  				resources :replies, only:[:new, :create, :show]
  			end
		  end
      resources :card, only: [:new, :show] do
        collection do
          post 'show', to: 'card#show'
          post 'pay', to: 'card#pay'
          post 'delete', to: 'card#delete'
        end
      end
  	end
  end

  namespace :on_store_users do
  	get '/form' => 'on_store_users#form', as: 'form'
    post '/form/ok' => 'on_store_users#form', as: 'form_ok'
    resources :on_store_users ,only:[:show, :edit, :update, :destroy] do
    	# get '/sales' => 'on_store_users#sales', as: 'sales'
      get '/home' => 'on_store_users#home', as: 'home'
      get '/withdrawal' => 'on_store_users#withdrawal', as: 'withdrawal'
      resources :on_store_user_images ,only:[:edit, :destroy]
    	resources :reviews, only:[:index, :destroy]
    	resources :inquiries, only:[:index, :show] do
  			resources :replies, only:[:new, :create]
  		end
  		resources :orders, except:[:create] do
        resources :order_images, only:[:destroy]
		 		resources :inquiries, except:[:destroy, :edit, :update] do
  				resources :replies, only:[:new, :create, :show]
  			end
		  end
  	end
  end

  namespace :on_store_users do
    devise_scope :on_store_user do
      get '/logout', to: 'sessions#destroy', as: 'logout'
    end
  end

  namespace :admins do
    get '', to:'admins#home'
    resources :orders, only:[:index, :show]
    resources :users, except:[:edit]
    resources :on_store_users, except:[:edit]
    resources :inquiries, only:[:index, :show]
    resources :reviews, only:[:index, :show, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	belongs_to :on_store_user
	belongs_to :user
	belongs_to :order, optional: true
	has_many :replies, dependent: :destroy

	validates :title,
            presence: true,
            length: { maximum: 50, message: "50文字以内で入力して下さい"}
  validates :body,
            presence: true,
            length: { maximum: 1000, message: "1000文字以内で入力して下さい"}
end

app/controllers/admins/inquiries_controller.rb
class Admins::InquiriesController < ApplicationController
	before_action :authenticate_admin!

	def index
		if params[:search].present?
			@q = Inquiry.ransack(search_params)
			@inquiries = @q.result(distinct: true).page(params[:page]).reverse_order
		else
			@q = Inquiry.ransack(params[:q])
			@inquiries = @q.result(distinct: true).page(params[:page]).reverse_order
		end
	end

	def show
		@inquiry = Inquiry.find(params[:id])
	end

	def search_params
    params.require(:q).permit(:s,
    													:user_name_cont,
    													:on_store_user_shop_name_cont,
    													:on_store_user_read_in,
    													:user_read_in)
  end
end

app/controllers/on_store_users/inquiries_controller.rb
class OnStoreUsers::InquiriesController < ApplicationController
	before_action :authenticate_on_store_user!
	# URLの直接入力を弾く
	before_action :ensure_correct_on_store_user
  def ensure_correct_on_store_user
    if current_on_store_user.id != params[:on_store_user_id].to_i
      redirect_to on_store_users_on_store_user_home_path(current_on_store_user)
    end
  end

	def new
		@inquiry = Inquiry.new
		@order = Order.find(params[:order_id])
		@inquiry_creat_url = "/on_store_users/on_store_users/#{current_on_store_user.id}/orders/#{@order.id}/inquiries"

		respond_to do |format|
	    format.html
	    format.js {render '/shared/inquiries/new.js.erb'}
	   end
	end

	def create
		@shop = current_on_store_user
		@order = Order.find(params[:inquiry][:order_id])
		user = @order.user
		inquiry = @shop.inquiries.new(inquiry_params)
		inquiry.user_id = user.id
		inquiry.order_id = @order.id
		inquiry.on_store_user_read = true
		@inquiries = @order.inquiries
		inquiry.save
		# エンドユーザへ通知
		UserMailer.with(user: user, inquiry: inquiry).new_inquiry.deliver_later

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		end
	end

	def index
		if params[:partial_key].present?
			@order = Order.find(params[:order_id])
			@shop = current_on_store_user
			@inquiries = @order.inquiries

			@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)

			respond_to do |format|
			  format.html
			  format.js {render '/shared/inquiries/inquiry.js.erb'}
			end
		else
			@user = current_on_store_user
			@q = @user.inquiries.ransack(params[:q])
			@inquiries = @q.result(distinct: true).page(params[:page]).reverse_order
			@search = current_on_store_user.orders.ransack(params[:search], search_key: :search)


			respond_to do |format|
			  format.html
			  format.js {render '/shared/inquiries/index.js.erb'}
			end
		end
	end

	def show
		@inquiry = Inquiry.find(params[:id])
		@user = @inquiry.user
		@shop = current_on_store_user
		@reply_new_url = "/on_store_users/on_store_users/#{@shop.id}/inquiries/#{@inquiry.id}/replies/new"
		if params[:partial_key].present?
			@partial_key = params[:partial_key]
			@order = Order.find(params[:order_id])
			@reply_new_url = "/on_store_users/on_store_users/#{@shop.id}/orders/#{@order.id}/inquiries/#{@inquiry.id}/replies/new"
		end
		# 既読処理
		@inquiry.on_store_user_read = true
		@inquiry.save

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/show.js.erb'}
		 end
	end

	private
	def inquiry_params
		params.require(:inquiry).permit(:on_store_user_id,
																		:order_id,
																		:user_id,
																		:title,
																		:body,
																		:user_read,
																		:on_store_user_read)
	end

	def search_params
    params.require(:q).permit(:s,
    													:user_name_cont,
    													:user_read_in,
    													:on_store_user_read_in)
  end
end

app/controllers/users/inquiries_controller.rb
class Users::InquiriesController < ApplicationController
	before_action :authenticate_user!
	# URL直入力弾く
	before_action :ensure_correct_user
	def ensure_correct_user
		if current_user.id != params[:user_id].to_i
			redirect_to root_path
		end
	end

	def new
		@inquiry = Inquiry.new
		@user = current_user
		@shop = OnStoreUser.find(params[:shop_id])
		@inquiry_creat_url = "/users/users/#{@user.id}/shops/#{@shop.id}/inquiry"
		if params[:order_id]
			@order = Order.find(params[:order_id])
		end

		respond_to do |format|
	    format.html
	    format.js {render '/shared/inquiries/new.js.erb'}
	   end
	end

	def create
		inquiry = current_user.inquiries.new(inquiry_params)
		@shop = OnStoreUser.find(params[:shop_id])
		inquiry.on_store_user_id = @shop.id
		inquiry.user_read = true
		# 注文前の問合せか後か
		if params[:inquiry][:order_id].present?
			@order = Order.find(params[:inquiry][:order_id])
			inquiry.order_id = @order.id
		end
		inquiry.save
		if params[:inquiry][:order_id].present?
			# partial表示のためのインスタンス変数（注文に対する）
			@inquiries = @order.inquiries
		else
			# partial表示のためのインスタンス変数（注文前）
			@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
		end
		# 出店者へ通知
		OnStoreUserMailer.with(on_store_user: @shop, inquiry: inquiry).new_inquiry.deliver_later

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		end
	end

	def index
		@user = current_user
		@q = @user.inquiries.ransack(params[:q])
		@inquiries = @q.result(distinct: true).page(params[:page]).reverse_order

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/index.js.erb'}
		end
	end

	def inquiry
		@shop = OnStoreUser.find(params[:shop_id])
		if params[:order_id] != nil
			@order = Order.find(params[:order_id])
			@inquiries = @order.inquiries
		else
			@inquiries = Inquiry.where(user_id: current_user, on_store_user_id:  @shop.id, order_id: nil)
		end

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/inquiry.js.erb'}
		 end
	end

	def show
		@user = current_user
		@shop = OnStoreUser.find(params[:shop_id])
		@inquiry = Inquiry.find(params[:id])
		@reply_new_url = "/users/users/#{@user.id}/inquiries/#{@inquiry.id}/replies/new"
		if params[:partial_key].present?
			@partial_key = params[:partial_key]
		end
		if params[:order_id].present?
			@order = Order.find(params[:order_id])
			@reply_new_url = "/users/users/#{@user.id}/orders/#{@order.id}/inquiries/#{@inquiry.id}/replies/new"
		end
		# 既読処理
		@inquiry.user_read = true
		@inquiry.save

		respond_to do |format|
		  format.html
		  format.js {render '/shared/inquiries/show.js.erb'}
		 end
	end

	private
	def inquiry_params
		params.require(:inquiry).permit(:on_store_user_id,
																		:order_id,
																		:user_id,
																		:title,
																		:body,
																		:is_read)
	end

	def search_params
    params.require(:q).permit(:s)
  end
end

app/helpers/admins/inquiries_helper.rb
module Admins::InquiriesHelper
end

app/helpers/on_store_users/inquiries_helper.rb
module OnStoreUsers::InquiriesHelper
end

app/helpers/users/inquiries_helper.rb
module Users::InquiriesHelper
end

app/views/admins/inquiries/index.html.erb
<div class="container margin-top">
	<div class="col-sm-12 col-xs-12">
		<div style="margin-bottom: 50px;" class="font-size2">
			<%= search_form_for(@q, url:admins_inquiries_path) do |f| %>
				<div class="form-group row">
					<%= f.label :user_name_cont, 'ユーザ名' %>
					<%= f.search_field :user_name_cont %>
					<%= f.label :on_store_user_shop_name_cont, '出店者(店舗名)' %>
					<%= f.search_field :on_store_user_shop_name_cont %>
				</div>
				<div class="form-group">
					<%= f.label :on_store_user_read_in, '出店者未読' %>
					<%= f.check_box 'on_store_user_read_in',{},checked_value = "false" %>
					<%= f.label :on_store_user_read_in, '出店者既読' %>
					<%= f.check_box 'on_store_user_read_in',{},checked_value = "true" %>
					<%= f.label :user_read_in, 'ユーザ未読' %>
					<%= f.check_box 'user_read_in',{},checked_value = "false" %>
					<%= f.label :user_read_in, 'ユーザ既読' %>
					<%= f.check_box 'user_read_in',{},checked_value = "true" %>
				</div>

				<%= f.submit "検索", name: "serch", class: "btn btn-default" %>
				<%= link_to "リセット", admins_inquiries_path, class: "btn btn-default" %>
			<% end %>
		</div>
		<div class="inquiries">
			<% if @inquiries.present? %>
				<table class="table">
					<thead  class="font-size2">
						<tr>
							<th>
								<%= sort_link(@q, :id, '問合せID') %>
							</th>
							<th>件名</th>
							<th>ユーザ名</th>
							<th>出店者（店舗名）</th>
							<th>問合せ日</th>
							<th>ユーザ（既読/未読）</th>
							<th>出店者（既読/未読）</th>
						</tr>
					</thead>
					<tbody  class="font-size2">
						<% @inquiries.each do |inquiry| %>
							<tr>
								<td><%= link_to inquiry.id, admins_inquiry_path(inquiry) %></td>
								<td><%= inquiry.title %></td>
								<td><%= inquiry.user.name %></td>
								<td><%= inquiry.on_store_user.shop_name %></td>
								<td><%= inquiry.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[inquiry.created_at.wday]}) %H:%M") %></td>
								<td>
									<% if inquiry.user_read == false %>
										<strong style="color: red">未読</strong>
									<% else %>
										<strong>既読</strong>
									<% end %>
								</td>
								<td>
									<% if inquiry.on_store_user_read == false %>
										<strong style="color: red">未読</strong>
									<% else %>
										<strong>既読</strong>
									<% end %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>

				<%= paginate @inquiries, class: "paginate" %>
			<% else %>
				まだお問合せはありません
			<% end %>
		</div>
	</div>
</div>

app/views/admins/inquiries/show.html.erb
<div class="container" style="margin: 50px 30px;">

	<div class="col-md-5 col-xs-8" style="margin: 50px 0 50px 0;">
		<h2 class="font-size4" style="padding-left: 10px;">問合せ詳細</h2>
	</div>

	<table class="table">
		<tbody class="font-size3">
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>問合せID</strong>
				</td>
				<td class="cell-body" style="padding-top: 15px; padding-bottom: 15px;">
					<%= @inquiry.id %>
				</td>
			</tr>
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>宛先</strong>
				</td>
				<td class="cell-body" style="padding-top: 15px; padding-bottom: 15px;">
					<%= @inquiry.on_store_user.shop_name %>
				</td>
			</tr>
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>差出人</strong>
				</td>
				<td class="cell-body" style="padding-top: 15px; padding-bottom: 15px;">
					<%= @inquiry.user.name %> (<%= @inquiry.user.name_kana %>)
				</td>
			</tr>
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>件名</strong>
				</td>
				<td class="cell-body" style="padding-top: 15px; padding-bottom: 15px;">
					<%= @inquiry.title %>
				</td>
			</tr>
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>注文ID</strong>
				</td>
				<td class="cell-body" style="padding-top: 15px; padding-bottom: 15px;">
					<% if @inquiry.order_id == nil %>
						注文前
					<% else %>
						<%= link_to @inquiry.order_id, admins_order_path(@inquiry.order_id) %>
					<% end %>
				</td>
			</tr>
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>最近の投稿日</strong>
				</td>
				<td class="cell-body" style="padding-top: 15px; padding-bottom: 15px;">
					<% if @inquiry.replies.count == 0 %>
						<%= @inquiry.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@inquiry.created_at.wday]}) %H:%M") %>
					<% else %>
						<%= @inquiry.replies.last.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@inquiry.replies.last.created_at.wday]}) %H:%M") %>
					<% end %>
				</td>
			</tr>
			<tr>
				<td class="cell-title" style="padding-top: 15px; padding-bottom: 15px;">
					<strong>本文：</strong>
				</td>
				<td></td>
			</tr>
			<tr>
				<td colspan="2" style="border-top: none; padding-top: 15px; padding-bottom: 15px;">
					<%= text_br(@inquiry.body) %>
				</td>
			</tr>
		</tbody>
	</table>

	<div id="reqlies">
		<% @inquiry.replies.each_with_index do |reply,index| %>
			<% index += 1 %>
			<table class="table">
				<tbody class="font-size3">
					<tr>
						<td style="padding-top: 15px; padding-bottom: 15px;">
							<strong>
								<%= index %>. 
								<!-- is_writerがfalseでユーザ投稿 -->
								<% if reply.is_writer == false %>
									 <%= reply.inquiry.user.name %> の返信
								<% else %>
									 <%= reply.inquiry.on_store_user.shop_name %> の返信
								<% end %>
							</strong>
						</td>
					</tr>
					<tr>
						<td style="padding-top: 15px; padding-bottom: 15px;">
							<strong>　投稿日時： </strong>
							<%= reply.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[reply.created_at.wday]}) %H:%M") %>
						</td>
					</tr>
					<tr>
						<td style="padding-top: 15px; padding-bottom: 15px;"><strong>　返信文：</strong></td>
						<td></td>
					</tr>
					<tr>
						<td colspan="2" style="padding-top: 15px; padding-bottom: 15px;">
							　<%= text_br(reply.body) %>
						</td>
					</tr>
				</tbody>
			</table>
		<% end %>
	</div>
</div>